<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <link rel="apple-touch-icon-precomposed" sizes="57x57" href="/img/favico/apple-touch-icon-57x57.png" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href=/"img/favico/apple-touch-icon-114x114.png" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/img/favico/apple-touch-icon-72x72.png" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/img/favico/apple-touch-icon-144x144.png" />
    <link rel="apple-touch-icon-precomposed" sizes="60x60" href="/img/favico/apple-touch-icon-60x60.png" />
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/img/favico/apple-touch-icon-120x120.png" />
    <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/img/favico/apple-touch-icon-76x76.png" />
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/img/favico/apple-touch-icon-152x152.png" />
    <link rel="icon" type="image/png" href="/img/favico/favicon-196x196.png" sizes="196x196" />
    <link rel="icon" type="image/png" href="/img/favico/favicon-96x96.png" sizes="96x96" />
    <link rel="icon" type="image/png" href="/img/favico/favicon_shdb_32x32.ico" sizes="32x32" />
    <link rel="icon" type="image/png" href="/img/favico/favicon_shdb_16x16.ico" sizes="16x16" />
    <link rel="icon" type="image/png" href="/img/favico/favicon-128.png" sizes="128x128" />
    <meta name="application-name" content="&nbsp;"/>
    <meta name="msapplication-TileColor" content="#FFFFFF" />
    <meta name="msapplication-TileImage" content="/img/favico/mstile-144x144.png" />
    <meta name="msapplication-square70x70logo" content="/img/favico/mstile-70x70.png" />
    <meta name="msapplication-square150x150logo" content="/img/favico/mstile-150x150.png" />
    <meta name="msapplication-wide310x150logo" content="/img/favico/mstile-310x150.png" />
    <meta name="msapplication-square310x310logo" content="/img/favico/mstile-310x310.png" />
    <meta charset="utf-8">
    <?php echo $this->headTitle('Smart Home Database ')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink()
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/grids-responsive-old-ie-min.css', "screen",  'lte IE 8')
        ->prependStylesheet($this->basePath() . '/css/grids-responsive-min.css', "screen","gt IE 8")
        ->prependStylesheet($this->basePath() . '/css/pure-min.css')

    ?>



    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/jquery-migrate-1.2.1.js')
        ->prependFile($this->basePath() . '/js/jquery-2.1.1.min.js')
        ->prependFile($this->basePath() . '/js/config.js');
    ; ?>

</head>
<body style="background-color: #f1f1f1">


<div class="content" style="padding: 0">



    <div class="row container">
        <?php echo $this->content; ?>
    </div>
</div> <!-- /container -->

<?php echo $this->inlineScript() ?>
</body>
</html>